### ISSUE TITLE
[問題案] 数当てゲーム

### ISSUE THREAD

**Issue by sotanishy** [puzzleknot/algorithm-puzzle#1]
問題: 1以上1000以下の数字 $x$ が隠されている．10回の質問をすることができる．1回の質問では，1以上1000以下の数字 $y$ を選んで質問できる． $x$ と $y$ の大小が返される．10回以内に $x=y$ とせよ

解法: 二分探索

**Comment by sotanishy** [comment]
initial commit でだいたい実装した．あとは解説ページを作ろうかなという感じ

**Comment by kitsuyaazuma** [comment]
@sotanishy 
main.js内で
```js
    if (x < y) {
        res = '<';
    } else if (x > y) {
        res = '>';
    } else {
        res = 'Correct!';
    }
```
となっているので数字入力無しでACが出てしまう模様です。
もう直されているかもしれませんが、一応報告です。

**Comment by milkcoffeen** [comment]
- 返答の「>」「<」とかは単語にしたほうが分かりやすいと思う。「High」「Low」など。

- 10回はシビアに感じる(正確に半分を計算するのはわりとだるい)のでもうちょっと余裕が欲しい。15回とかに設定して解説では「10回で必ずできます」と言うなど。

**Comment by sotanishy** [comment]
質問回数は15回にします．

`><` は別に今のままでよいのでは？という気持ちでいる．

**Comment by milkcoffeen** [comment]
好みの問題かもしれないけど「>」だけだと少しわかりづらく感じた。
「x>y」「x<y」みたいなのをそのまま出力するのはどうですか

**Comment by sotanishy** [comment]
それは 👍
